// ============================================================
// app/servidor/historico/dados-mock.ts
// Dados mockados para o módulo de Histórico de Trabalho
// Em produção, esses dados viriam da API
// ============================================================

import { RegistroAtividade, EstatisticasHistorico } from '../../tipos/historico';

export const registrosMock: RegistroAtividade[] = [
  {
    id: 'reg-001',
    numeroProcesso: '0001234-56.2024.8.00.0001',
    partes: 'João da Silva vs. Empresa ABC Ltda',
    data: '09/02/2026',
    hora: '09:15',
    categoriaAcao: 'despacho',
    descricaoAcao: 'Minutado despacho de citação do réu para apresentar contestação no prazo de 15 dias',
    observacao: 'Réu com endereço atualizado conforme AR positivo',
    servidor: 'Maria Silva',
    status: 'concluido',
    temLembrete: true,
    dataLembrete: '24/02/2026',
    descricaoLembrete: 'Verificar se réu apresentou contestação',
  },
  {
    id: 'reg-002',
    numeroProcesso: '0007890-12.2024.8.00.0001',
    partes: 'Maria Oliveira vs. Banco XYZ S.A.',
    data: '09/02/2026',
    hora: '10:30',
    categoriaAcao: 'juntada',
    descricaoAcao: 'Juntada de documentos comprobatórios apresentados pelo autor (laudos médicos e receituários)',
    servidor: 'Maria Silva',
    status: 'concluido',
    temLembrete: false,
  },
  {
    id: 'reg-003',
    numeroProcesso: '0005678-90.2024.8.00.0001',
    partes: 'Pedro Santos vs. Construtora DEF S.A.',
    data: '09/02/2026',
    hora: '11:00',
    categoriaAcao: 'intimacao',
    descricaoAcao: 'Expedida intimação para o perito judicial apresentar laudo técnico',
    observacao: 'Prazo de 30 dias para apresentação do laudo',
    servidor: 'Maria Silva',
    status: 'em_andamento',
    temLembrete: true,
    dataLembrete: '11/03/2026',
    descricaoLembrete: 'Cobrar laudo do perito',
  },
  {
    id: 'reg-004',
    numeroProcesso: '0002345-67.2024.8.00.0001',
    partes: 'Ana Costa vs. Seguradora GHI Ltda',
    data: '08/02/2026',
    hora: '14:20',
    categoriaAcao: 'certidao',
    descricaoAcao: 'Certidão de decurso de prazo - autor não se manifestou sobre documentos juntados',
    servidor: 'Maria Silva',
    status: 'concluido',
    temLembrete: false,
  },
  {
    id: 'reg-005',
    numeroProcesso: '0003456-78.2024.8.00.0001',
    partes: 'Carlos Mendes vs. Prefeitura Municipal',
    data: '08/02/2026',
    hora: '15:45',
    categoriaAcao: 'oficio',
    descricaoAcao: 'Expedido ofício requisitório ao INSS para fornecimento de informações cadastrais',
    observacao: 'Ofício nº 123/2026 - enviado via SEEU',
    servidor: 'Maria Silva',
    status: 'em_andamento',
    temLembrete: true,
    dataLembrete: '22/02/2026',
    descricaoLembrete: 'Verificar resposta do INSS ao ofício',
  },
  {
    id: 'reg-006',
    numeroProcesso: '0004567-89.2024.8.00.0001',
    partes: 'Empresa JKL vs. Fornecedor MNO',
    data: '07/02/2026',
    hora: '09:00',
    categoriaAcao: 'calculo',
    descricaoAcao: 'Elaborada planilha de cálculos de liquidação de sentença com atualização monetária',
    observacao: 'Valores atualizados até 01/2026 pelo IPCA-E',
    servidor: 'Maria Silva',
    status: 'concluido',
    temLembrete: false,
  },
  {
    id: 'reg-007',
    numeroProcesso: '0001234-56.2024.8.00.0001',
    partes: 'João da Silva vs. Empresa ABC Ltda',
    data: '07/02/2026',
    hora: '11:30',
    categoriaAcao: 'publicacao',
    descricaoAcao: 'Publicação do despacho no DJE - disponibilização em 07/02, publicação em 08/02',
    servidor: 'Maria Silva',
    status: 'concluido',
    temLembrete: false,
  },
  {
    id: 'reg-008',
    numeroProcesso: '0008901-23.2024.8.00.0001',
    partes: 'Lucia Ferreira vs. Plano de Saúde PQR',
    data: '06/02/2026',
    hora: '16:00',
    categoriaAcao: 'audiencia',
    descricaoAcao: 'Realizada audiência de conciliação - acordo parcial entre as partes',
    observacao: 'Partes acordaram sobre urgência do tratamento. Valores a serem discutidos em nova audiência.',
    servidor: 'Maria Silva',
    status: 'concluido',
    temLembrete: true,
    dataLembrete: '20/02/2026',
    descricaoLembrete: 'Nova audiência para discussão de valores',
  },
  {
    id: 'reg-009',
    numeroProcesso: '0009012-34.2024.8.00.0001',
    partes: 'Roberto Almeida vs. Concessionária STU',
    data: '06/02/2026',
    hora: '10:15',
    categoriaAcao: 'cumprimento',
    descricaoAcao: 'Verificado cumprimento da decisão liminar - réu comprovou adequação do serviço',
    servidor: 'Maria Silva',
    status: 'concluido',
    temLembrete: false,
  },
  {
    id: 'reg-010',
    numeroProcesso: '0005678-90.2024.8.00.0001',
    partes: 'Pedro Santos vs. Construtora DEF S.A.',
    data: '05/02/2026',
    hora: '14:00',
    categoriaAcao: 'decisao',
    descricaoAcao: 'Minutada decisão interlocutória deferindo produção de prova pericial',
    observacao: 'Nomeado perito eng. civil conforme cadastro do tribunal',
    servidor: 'Maria Silva',
    status: 'concluido',
    temLembrete: false,
  },
];

export const estatisticasMock: EstatisticasHistorico = {
  totalRegistros: 47,
  registrosHoje: 3,
  processosAtendidos: 8,
  lembretesAtivos: 4,
};
